import Head from 'next/head'
import { HomePage } from '../src/component/home/home-page'

export default function Home({ data }: any) {
  return (
    <div>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </div>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json')
  // console.log(events_categories)

  return {
    props: {
      data: events_categories,
    },
  }
}
